version: 2.1

orbs:
  orb-tools: circleci/orb-tools@2.0.0
  cli: circleci/circleci-cli@0.0.1

jobs:
  validate:
    executor: cli/default
    steps:
      - checkout

      - orb-tools/validate:
          orb-path: src/@orb.yml

  orb-tools/publish:
    executor: cli/default
    steps:
    - orb-path: src/@orb.yml
    - orb-ref: circleci/aws-cli@dev:$CIRCLE_BRANCH
    - publish-token-variable: $CIRCLE_TOKEN

workflows:
  version: 2
  validate-publish:
    jobs:
      - validate

      - orb-tools/publish:
          requires:
            - validate