version: 2.1

orbs:
  orb-tools: circleci/orb-tools@volatile
  cli: circleci/circleci-cli@volatile

jobs:
  validate:
    executor: cli/default
    steps:
      - checkout

      - orb-tools/validate:
          orb-path: src/@orb.yml

  publish:
    executor: cli/default
    steps:
      - checkout

      - orb-tools/publish:
          orb-path: src/@orb.yml
          orb-ref: circleci/aws-cli@dev:$CIRCLE_BRANCH
          token-variable: $CIRCLE_TOKEN

workflows:
  version: 2
  validate-publish:
    jobs:
      - validate

      - publish:
          requires:
            - validate
