description: |
  configure and store AWS credentials in
  ~/.aws/credentials and ~/.aws/config

parameters:
  profile-name:
    description: Profile name to be configured.
    type: string
    default: "default"

  aws-access-key-id:
    description: |
      AWS access key id for IAM role. Set this to the name of
      the environment variable you will use to hold this
      value, i.e. $AWS_ACCESS_KEY.
    type: string
    default: $AWS_ACCESS_KEY_ID

  aws-secret-access-key:
    description: |
      AWS secret key for IAM role. Set this to the name of
      the environment variable you will set to hold this
      value, i.e. $AWS_SECRET_ACCESS_KEY.
    type: string
    default: $AWS_SECRET_ACCESS_KEY

  aws-region:
    description: |
      AWS region to operate in
      (defaults to the value of $AWS_REGION)
    type: string
    default: $AWS_REGION

steps:
  - run:
      name: configure AWS Access Key ID
      command: |
        aws configure set aws_access_key_id \
        << parameters.aws-access-key-id >> \
        --profile << parameters.profile-name >>

  - run:
      name: configure AWS Secret Access Key
      command: |
        aws configure set aws_secret_access_key \
        << parameters.aws-secret-access-key >> \
        --profile << parameters.profile-name >>

  - run:
      name: Configure AWS default region
      command: |
        aws configure set region << parameters.region >> \
        --profile << parameters.profile-name >>
